### ISSUE TITLE
np.matrix is not supported

### ISSUE THREAD

**Issue by amnghn** [nowling-lab/asaph#12]
Hi, 
I am running asaph on our HPC cluster with the following command:

```
asaph_pca \
	--workdir $WORK_DIR \
	--vcf-gz $VCF
```
But after about an hour the pipeline stopped and gave me this error: 

```
Traceback (most recent call last):
  File "/lisc/app/asaph/2.0/bin/asaph_pca", line 201, in <module>
    proj = train_pca(features, args)
  File "/lisc/app/asaph/2.0/bin/asaph_pca", line 108, in train_pca
    projections = pca.fit_transform(feature_matrix)
  File "/lisc/app/asaph/2.0/sklearn/utils/_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/lisc/app/asaph/2.0/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/lisc/app/asaph/2.0/sklearn/decomposition/_pca.py", line 474, in fit_transform
    U, S, _, X, x_is_centered, xp = self._fit(X)
  File "/lisc/app/asaph/2.0/sklearn/decomposition/_pca.py", line 511, in _fit
    X = self._validate_data(
  File "/lisc/app/asaph/2.0/sklearn/base.py", line 633, in _validate_data
    out = check_array(X, input_name="X", **check_params)
  File "/lisc/app/asaph/2.0/sklearn/utils/validation.py", line 841, in check_array
    raise TypeError(
TypeError: np.matrix is not supported. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
```

I think this is because np.matrix is not supported anymore. Right? Do you have any plans to update the script? 

Also,  I wanted to point out that when I run it with the following command according to the [second  tutorial](https://github.com/nowling-lab/asaph/blob/main/tutorials/pca.md#import-data-and-perform-pca-principal-component-analysis): 

```
asaph_pca \
	--workdir $WORK_DIR \
	pca \
	--vcf $VCF
```

I returns this error message: 

```
asaph_pca: error: unrecognized arguments: pca
```

It would be great if you could update the tutorial as well.

Thank you so much in advance for your help.

**Comment by rnowling** [comment]
I don't think either of this are due to Asaph itself.  Asaph doesn't construct any Numpy matrices (just arrays).  Secondly, the asaph_pca script does take the pca argument...
